# Generated by Django 5.2.7 on 2025-11-04 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата оплаты"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("course", "Курс"),
                            ("lesson", "Урок"),
                            ("subscription", "Подписка"),
                        ],
                        max_length=15,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        max_length=255, verbose_name="Название курса/урока"
                    ),
                ),
                (
                    "item_description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма оплаты"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                        max_length=10,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID платежа в Stripe"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=True, verbose_name="Оплата завершена"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-payment_date"],
            },
        ),
    ]
