# Generated by Django 5.2.7 on 2025-11-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Telegram Chat ID"
            ),
        ),
    ]
