# Generated by Django 5.2.7 on 2025-11-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_telegram_chat_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
