# Dockerfile.nginx
FROM nginx:1.25-alpine

# Копирование конфигурации nginx
COPY nginx/nginx.conf /etc/nginx/nginx.conf
RUN rm /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]