# Generated by Django 5.2.7 on 2026-02-04 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Ежедневно"),
                    (2, "Раз в 2 дня"),
                    (3, "Раз в 3 дня"),
                    (4, "Раз в 4 дня"),
                    (5, "Раз в 5 дней"),
                    (6, "Раз в 6 дней"),
                    (7, "Раз в неделю"),
                ],
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Вознаграждение"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Время на выполнение (секунды)",
            ),
        ),
    ]
